# -*- coding: utf-8 -*-
"""DJ_collab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNvOsfwlUmhT-T_Znx7VeTYu3_taTE67
"""

!pip install -q torch torchvision matplotlib numpy diffusers transformers accelerate

import torch
import matplotlib.pyplot as plt
from diffusers import DiffusionPipeline

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Device:', device)
if device.type == 'cuda':
    print('GPU   :', torch.cuda.get_device_name(0))

from diffusers import DiffusionPipeline

# Load a pre-trained Stable Diffusion pipeline
pipeline = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True,
)

pipeline = pipeline.to(device)

"""Common negative prompt"""

negative_prompt = "low quality, blurry, distorted, bad anatomy, text, watermark, signature, deformed"

def generate_cover(act_name, prompt, negative_prompt, seed=42):
    g = torch.Generator(device).manual_seed(seed)
    img = pipeline(prompt=prompt, negative_prompt=negative_prompt,
                   num_inference_steps=30, guidance_scale=7.5,
                   generator=g).images[0]
    img.save(f"{act_name.replace(' ', '_')}.png")
    return img

def show(img, title, size=6):
    plt.figure(figsize=(size, size))
    plt.imshow(img)
    plt.axis('off')
    plt.title(title, fontsize=10)
    plt.show()

prompt = "Just basic dramatic classical cover"

# Generate an image
test_img = generate_cover("test_image", prompt)
show(test_img, 'Test: "Just basic dramatic classical cover"')

"""6 fictional music acts"""

ACTS = {
    "lofi_bedroom_pop": {
        "artist": "Pillow Static",
        "album": "Sunday Reruns",
        "genre": "Lo-fi bedroom pop",
        "prompt": (
            "cozy teenage bedroom at dusk, cassette player and tangled fairy lights on a windowsill, "
            "rain on the glass, soft film grain, muted pastel palette of dusty pink, faded teal and warm amber, "
            "nostalgic dreamy mood, lo-fi anime-inspired illustration, gentle window light"
        ),
    },
    "dramatic_classical": {
        "artist": "The Velvet Requiem",
        "album": "Ashes of the Overture",
        "genre": "Dramatic classical",
        "prompt": (
            "grand piano engulfed by a violent ocean storm at night, shattered marble statues sinking in waves, "
            "dark romanticism, cinematic oil painting, dramatic chiaroscuro lighting, "
            "deep crimson, obsidian black and fractured gold palette, tempestuous awe-inspiring mood"
        ),
    },
    "chaotic_punk": {
        "artist": "Dumpster Ballet",
        "album": "Refund Denied",
        "genre": "Chaotic punk",
        "prompt": (
            "ripped xerox collage of a screaming crowd and a smashed guitar, safety pins and torn tape, "
            "harsh photocopy texture, DIY zine cut-and-paste style, "
            "acid yellow, black and blood red palette, aggressive anarchic mood, high contrast grain"
        ),
    },
    "mysterious_ambient": {
        "artist": "Halocline",
        "album": "Below the Thermocline",
        "genre": "Mysterious ambient",
        "prompt": (
            "vast empty fog-covered lake at 4am, a single faint light under the water surface, "
            "minimalist long-exposure photography, deep indigo, slate grey and pale cyan palette, "
            "eerie meditative mood, negative space, soft gradients, endless horizon"
        ),
    },
    "cheesy_80s_pop_duo": {
        "artist": "Neon Cousins",
        "album": "Call Me After Aerobics",
        "genre": "Cheesy 80s pop duo",
        "prompt": (
            "two confident pop singers in shoulder-padded metallic jackets, back to back pose, "
            "airbrushed 1980s studio portrait, laser grid background, "
            "hot pink, electric blue and chrome palette, glamorous over-the-top mood, soft glow, retro gloss"
        ),
    },
    "kids_rocknroll": {
        "artist": "The Wiggly Amps",
        "album": "Bedtime Is Cancelled!!",
        "genre": "Rock'n'roll for kids (wymyślony)",
        "prompt": (
            "cartoon animal band on a cardboard stage, dinosaur drummer and rabbit guitarist mid-jump, "
            "bold playful children's book illustration, thick outlines, confetti in the air, "
            "primary red, sunny yellow and sky blue palette, joyful energetic mood"
        ),
    },
}

for key, act in ACTS.items():
    print(f"🎵 {act['artist']} — „{act['album']}”  [{act['genre']}]")

"""Album cover generator"""

cover_images = {}
for key, act in ACTS.items():
    print(f"Generuję: {act['artist']} …")
    cover_images[key] = generate_cover(f"cover_{key}", act["prompt"], negative_prompt)

fig, axes = plt.subplots(2, 3, figsize=(15, 10))
for ax, (key, act) in zip(axes.flat, ACTS.items()):
    ax.imshow(cover_images[key])
    ax.axis('off')
    ax.set_title(f"{act['artist']}\n„{act['album']}”", fontsize=9)
plt.suptitle("6 fikcyjnych zespołów — po jednej okładce", fontsize=13)
plt.tight_layout()
plt.show()

BEST = "dramatic_classical"
seeds = [7, 42, 123, 999]
variations = []
for s in seeds:
    print(f"Seed {s} …")
    variations.append(generate_cover(f"best_{BEST}_seed{s}", ACTS[BEST]["prompt"], negative_prompt, seed=s))

fig, axes = plt.subplots(1, 4, figsize=(20, 5))
for ax, img, s in zip(axes, variations, seeds):
    ax.imshow(img)
    ax.axis('off')
    ax.set_title(f"seed={s}", fontsize=10)
plt.suptitle(f"{ACTS[BEST]['artist']} — ten sam prompt, 4 różne seedy", fontsize=13)
plt.tight_layout()
plt.show()

print("""
OBSERWACJE (uzupełnij po obejrzeniu własnych wyników):
• STAŁE: fortepian jako główny motyw, sztorm/woda, paleta crimson-czerń-złoto,
  malarski styl chiaroscuro, ogólny dramatyczny nastrój.
• ZMIENNE: kompozycja i kąt kamery, liczba i położenie posągów, faza sztormu
  (fale vs. mgła), proporcja złota do czerwieni, poziom szczegółu fal.
Wniosek: prompt kontroluje TREŚĆ i STYL, seed kontroluje konkretną KOMPOZYCJĘ.
""")

bad_img = generate_cover("bad_prompt", "music", negative_prompt)
show(bad_img, 'Fatalny prompt: "music"')

print("""
DOKUMENTACJA (uzupełnij po obejrzeniu wyniku):
Przy prompcie "music" model nie ma żadnych wskazówek co do stylu, koloru,
nastroju ani obiektu — spada więc na najczęstsze skojarzenia z datasetu:
typowo nuty, instrumenty (gitara/pianino), słuchawki, generyczne gradienty.
Kompozycja bywa chaotyczna, elementy zlewają się. To pokazuje, że jakość
promptu (styl + kolory + nastrój + obrazowanie) bezpośrednio przekłada się
na spójność wyniku — dokładnie o to chodzi w punktach 3 vs 5 zadania.
""")

import base64
from IPython.display import HTML, display

FAVOURITES = [
    {
        "file": f"best_{BEST}_seed42.png",
        "artist": "The Velvet Requiem",
        "album": "Ashes of the Overture",
        "genre": "Dramatic Classical",
        "tracks": ["Overture in Flames", "Marble Lungs", "Storm Sonata No. 9",
                   "Requiem for the Undertow", "Gilded Wreckage", "Final Curtain, First Light"],
    },
    {
        "file": "cover_mysterious_ambient.png",
        "artist": "Halocline",
        "album": "Below the Thermocline",
        "genre": "Mysterious Ambient",
        "tracks": ["Descent", "Four A.M. Water", "Pressure Hymn",
                   "The Light Below", "Sonar Ghosts", "Surface (Reprise)"],
    },
    {
        "file": "cover_cheesy_80s_pop_duo.png",
        "artist": "Neon Cousins",
        "album": "Call Me After Aerobics",
        "genre": "80s Pop",
        "tracks": ["Call Me After Aerobics", "Cassette Heart", "Leg Warmer Love",
                   "Payphone Serenade", "VHS Sunset", "Rewind Me"],
    },
]

def img_to_b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()

cards = ""
for i, fav in enumerate(FAVOURITES, 1):
    tracks_html = "".join(
        f"<li><span class='no'>{j:02d}</span>{t}</li>"
        for j, t in enumerate(fav["tracks"], 1)
    )
    cards += f"""
    <article class="sleeve">
      <div class="cover-wrap">
        <img src="data:image/png;base64,{img_to_b64(fav['file'])}" alt="{fav['album']}">
        <div class="vinyl"></div>
      </div>
      <div class="meta">
        <p class="genre">{fav['genre']} · LP {i:02d}</p>
        <h2>{fav['album']}</h2>
        <p class="artist">{fav['artist']}</p>
        <ol class="tracks">{tracks_html}</ol>
      </div>
    </article>"""

html = f"""<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI DJ — Curated Selection</title>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,600;1,500&family=Space+Grotesk:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root {{
    --ink: #17141f;
    --paper: #efe8da;
    --gold: #c9a45c;
    --wine: #7a2c3b;
    --fog:  #9a94a8;
  }}
  * {{ box-sizing: border-box; margin: 0; }}
  body {{
    background: var(--ink);
    color: var(--paper);
    font-family: 'Space Grotesk', sans-serif;
    padding: 56px 24px 80px;
  }}
  header {{ max-width: 1100px; margin: 0 auto 48px; }}
  header p.label {{
    letter-spacing: .35em; text-transform: uppercase;
    font-size: 11px; color: var(--gold); margin-bottom: 14px;
  }}
  header h1 {{
    font-family: 'Cormorant Garamond', serif;
    font-size: clamp(38px, 6vw, 64px);
    font-weight: 600; line-height: 1.05;
  }}
  header h1 em {{ font-style: italic; color: var(--gold); }}
  header p.sub {{ margin-top: 14px; color: var(--fog); max-width: 52ch; }}
  .rack {{
    max-width: 1100px; margin: 0 auto;
    display: grid; gap: 40px;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  }}
  .sleeve {{
    background: #1f1b29;
    border: 1px solid #2c2738;
    padding: 18px 18px 26px;
  }}
  .cover-wrap {{ position: relative; aspect-ratio: 1; overflow: visible; }}
  .cover-wrap img {{
    position: relative; z-index: 2;
    width: 100%; aspect-ratio: 1; object-fit: cover; display: block;
    box-shadow: 0 12px 30px rgba(0,0,0,.55);
  }}
  /* sygnatura: winyl wysuwający się z okładki po najechaniu */
  .vinyl {{
    position: absolute; top: 4%; left: 0; z-index: 1;
    width: 92%; aspect-ratio: 1; border-radius: 50%;
    background:
      radial-gradient(circle at center, var(--gold) 0 12%, #0c0a10 13% 15%,
        #191521 16% 100%);
    background-blend-mode: normal;
    box-shadow: inset 0 0 0 1px #000;
    transition: transform .5s cubic-bezier(.2,.7,.2,1);
  }}
  .sleeve:hover .vinyl {{ transform: translateX(26%) rotate(40deg); }}
  @media (prefers-reduced-motion: reduce) {{
    .vinyl {{ transition: none; }}
    .sleeve:hover .vinyl {{ transform: none; }}
  }}
  .meta {{ margin-top: 22px; }}
  .genre {{
    font-size: 10px; letter-spacing: .3em; text-transform: uppercase;
    color: var(--gold); margin-bottom: 8px;
  }}
  .meta h2 {{
    font-family: 'Cormorant Garamond', serif;
    font-size: 27px; font-weight: 600; line-height: 1.1;
  }}
  .artist {{ color: var(--fog); margin: 4px 0 16px; font-size: 14px; }}
  .tracks {{ list-style: none; padding: 0; border-top: 1px solid #2c2738; }}
  .tracks li {{
    display: flex; gap: 14px; align-items: baseline;
    padding: 7px 0; font-size: 13.5px;
    border-bottom: 1px solid #2c2738;
  }}
  .tracks .no {{ color: var(--wine); font-size: 11px; letter-spacing: .1em; }}
</style>
</head>
<body>
  <header>
    <p class="label">AI DJ · Selekcja kuratorska</p>
    <h1>Three sleeves,<br><em>three worlds.</em></h1>
    <p class="sub">Trzy ulubione okładki wygenerowane przez Stable Diffusion XL —
    każda z fikcyjnym albumem i tracklistą. Najedź na okładkę, żeby wysunąć płytę.</p>
  </header>
  <section class="rack">{cards}</section>
</body>
</html>"""

with open("gallery.html", "w", encoding="utf-8") as f:
    f.write(html)

display(HTML(html))                     # podgląd bezpośrednio w Colab
print("💾 Zapisano gallery.html — możesz pobrać plik z panelu Files w Colab.")

"""### Zapisywanie wygenerowanych plików na Google Drive (opcjonalne)

Jeśli chcesz zapisać wygenerowane okładki (`.png`) i plik `gallery.html` na swoim Dysku Google, uruchom poniższą komórkę. Najpierw podłączymy Dysk Google, a następnie skopiujemy pliki do wskazanego folderu.
"""

from google.colab import drive
import os
import shutil

# 1. Podłącz Dysk Google
drive.mount('/content/drive')

# 2. Zdefiniuj ścieżkę do folderu na Dysku Google, gdzie chcesz zapisać pliki
#    Możesz zmienić 'AI_AlbumCovers' na dowolną nazwę folderu.
save_dir = '/content/drive/MyDrive/AI_AlbumCovers'

# Utwórz folder, jeśli nie istnieje
os.makedirs(save_dir, exist_ok=True)

# 3. Skopiuj wygenerowane pliki PNG
for key in ACTS:
    src_file_cover = f"/content/cover_{key}.png"
    if os.path.exists(src_file_cover):
        shutil.copy(src_file_cover, save_dir)
        print(f"Skopiowano: {os.path.basename(src_file_cover)}")

# Skopiuj pliki dla BEST (variations)
for s in seeds:
    src_file_best = f"/content/best_{BEST}_seed{s}.png"
    if os.path.exists(src_file_best):
        shutil.copy(src_file_best, save_dir)
        print(f"Skopiowano: {os.path.basename(src_file_best)}")

# Skopiuj plik bad_prompt.png
src_file_bad = "/content/bad_prompt.png"
if os.path.exists(src_file_bad):
    shutil.copy(src_file_bad, save_dir)
    print(f"Skopiowano: {os.path.basename(src_file_bad)}")

# 4. Skopiuj plik gallery.html
src_gallery = "/content/gallery.html"
if os.path.exists(src_gallery):
    shutil.copy(src_gallery, save_dir)
    print(f"Skopiowano: {os.path.basename(src_gallery)}")

print(f"Wszystkie wygenerowane pliki zostały skopiowane do: {save_dir}")